### PR TITLE
Implemented Meta component

### PR DESCRIPTION
**Pull request by JAjorgbor**
I made the following changes in this branch:

- **Implemented** : `Meta.jsx` component for dynamic meta description and page titles
- **Added**: `.babelrc` file to portal directory and `"next/babel","next/core-web-vitals"` to `.eslint.js` to remove eslint babel error flagging

### CODE REVIEW

**Comment by JAjorgbor** [comment]
@suleinsights @anaotaye I just made a commit for the title prefix and title suffix  props

**Comment by suleinsights** [comment]
@JAjorgbor I have made the recommended improvements.

**Comment by suleinsights** [comment]
@anaotaye we're waiting for your own feedback. What do you think?
@JAjorgbor explain to @KMF21 through whatever medium, and then let Ikoojo pull the repo, investigate and give his feedback on what he thinks too.

@KMF21 kindly share your feedback under this thread.

**Comment by KMF21** [comment]
Okk okk!

**Pull request merged**
